SECRET_KEY = 'b7c3-483e-a03c-ad915e36c2a5'
main_db = 'sqlite:///C:\\Users\\Home2\\PycharmProjects\\Projects\\WEB_project\\data\\newDB.db'
gma_db = "sqlite:///D:\\Users\\Home\\Desktop\\WEB_project\\data\\newDB.db"
yana_db = 'sqlite:///C:\\Users\\Яна\\Desktop\\WEB\\data\\newDB.db'
sharaga_db = 'sqlite:///C:\\Users\\user\\Desktop\\asdf\\wb\\data\\newDB.db'
DEFAULT_PROFILE_IMAGE = '/static/img/default.jpg'
APIROUTE = '/api/v1.0'
MAX_FILE_SIZE = 16 * 1024 * 1024
APIKEY_DAYS_VALID = 365
