"""empty message

Revision ID: 7e95a7c33640
Revises: 7ff0bcca51e1
Create Date: 2022-04-24 23:19:18.640030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e95a7c33640'
down_revision = '7ff0bcca51e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('apikeys', 'testfield')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apikeys', sa.Column('testfield', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
