"""empty message

Revision ID: 7f417800e558
Revises: 1ab52f3df10a
Create Date: 2022-04-30 02:30:59.835475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f417800e558'
down_revision = '1ab52f3df10a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apex_orders', sa.Column('used_promo', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('apex_orders', 'used_promo')
    # ### end Alembic commands ###
