"""empty message

Revision ID: 7ff0bcca51e1
Revises: 
Create Date: 2022-04-24 23:18:43.661986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ff0bcca51e1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apikeys', sa.Column('testfield', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('apikeys', 'testfield')
    # ### end Alembic commands ###
